# Local development configuration
# Add your local database credentials here
# Do not commit this file to version control

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your_local_db
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop  # or update for dev
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size: 5